In [20]:
from numpy import *                           #Setting the training and testing sets
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
iris=load_iris()
iris.data=iris.data[:100,:2]
iris.data=insert(iris.data,0,1,axis=1)
iris.target=iris.target[:100]
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,train_size=70,random_state=1000)
print(x_train)
#print(x_train)
#x_train.shape
#y_train.shape
print(y_test)

[[ 1.   4.6  3.1]
 [ 1.   6.2  2.2]
 [ 1.   6.6  3. ]
 [ 1.   4.6  3.4]
 [ 1.   4.3  3. ]
 [ 1.   4.7  3.2]
 [ 1.   5.7  2.8]
 [ 1.   4.4  2.9]
 [ 1.   4.8  3.4]
 [ 1.   4.9  2.4]
 [ 1.   4.8  3. ]
 [ 1.   6.3  3.3]
 [ 1.   4.7  3.2]
 [ 1.   5.4  3.9]
 [ 1.   5.1  3.5]
 [ 1.   5.7  4.4]
 [ 1.   5.2  2.7]
 [ 1.   5.2  3.5]
 [ 1.   5.1  3.8]
 [ 1.   5.9  3.2]
 [ 1.   5.   2.3]
 [ 1.   5.7  3.8]
 [ 1.   5.5  2.6]
 [ 1.   6.4  2.9]
 [ 1.   5.4  3.4]
 [ 1.   6.1  3. ]
 [ 1.   5.   3.3]
 [ 1.   5.   3.5]
 [ 1.   6.8  2.8]
 [ 1.   5.1  3.3]
 [ 1.   5.8  2.7]
 [ 1.   5.4  3.9]
 [ 1.   5.   3.4]
 [ 1.   5.1  2.5]
 [ 1.   5.   3.4]
 [ 1.   5.1  3.7]
 [ 1.   7.   3.2]
 [ 1.   6.2  2.9]
 [ 1.   5.2  4.1]
 [ 1.   6.9  3.1]
 [ 1.   4.8  3.4]
 [ 1.   5.6  2.5]
 [ 1.   5.7  3. ]
 [ 1.   5.8  4. ]
 [ 1.   6.   2.9]
 [ 1.   5.4  3.7]
 [ 1.   5.7  2.6]
 [ 1.   6.7  3. ]
 [ 1.   5.5  2.4]
 [ 1.   5.2  3.4]
 [ 1.   5.5  2.4]
 [ 1.   4.8  3.1]
 [ 1.   5.4  3.4]
 [ 1.   4.5  2.3]
 [ 1.   6.6  2.9]
 [ 1.   4.

In [58]:
theta=random.random((3,1))  #initializing parameters,rate and defining the hypothesis function
print(theta)
rate=0.03
def model(array):
    value=0
    for j in range(3):
        value=value+(array[j]*theta[j][0])
    rvalue=1/(1+exp(-value))
    return rvalue
def output(array):
    value=0
    for j in range(3):
        value=value+(array[j]*theta[j][0])
    if(value>=0):
        return(1)
    else:
        return(0)
def cost(theta):
    sum=0
    for i in range(70):
        sum=sum+(y_train[i]*log(model(x_train[i])))+((1-y_train[i])*log(1-model(x_train[i])))
    return(sum)    

[[ 0.39101268]
 [ 0.72010743]
 [ 0.0078061 ]]


In [69]:
#old_cost=0
#i=0
#while((i>-1)and(old_cost-cost(theta)>=0.000003)):           #Gradient Ascent for Parameter Updation
 #   old_cost=cost(theta)
    #for j in range(3):
        #theta[j][0]=theta[j][0]+(rate*(y_train[i]-model(x_train[i]))*x_train[i][j])
    #print("training end",i)
    #print(cost(theta))
    #if(i==69):
        #i=0
    #else:
        #i=i+1
        

training end 0
-44.4340105079
training end 1
-42.2360207589


In [72]:
for k in range(10):
    for i in range(70):
        for j in range(3):
            theta[j][0]=theta[j][0]+(rate*(y_train[i]-model(x_train[i]))*x_train[i][j])
        print("training end",i)
        print(cost(theta))
    print("------------------------------------------")    

training end 0
-43.2562407315
training end 1
-42.0427047026
training end 2
-45.6118555389
training end 3
-41.4444964591
training end 4
-42.5557918975
training end 5
-46.3050958299
training end 6
-41.0559391363
training end 7
-42.9800569741
training end 8
-46.885527503
training end 9
-41.1606007667
training end 10
-44.4522720335
training end 11
-40.8396032104
training end 12
-41.4482513594
training end 13
-44.9249396529
training end 14
-49.4066415721
training end 15
-52.9804594674
training end 16
-41.9222037558
training end 17
-45.9946412364
training end 18
-50.0159609457
training end 19
-40.2213037127
training end 20
-40.5838511397
training end 21
-40.7504799029
training end 22
-40.1795972012
training end 23
-43.5334098933
training end 24
-39.5478100562
training end 25
-41.675288624
training end 26
-39.4260081712
training end 27
-41.7847467342
training end 28
-39.1457196842
training end 29
-40.1998104523
training end 30
-39.1459333301
training end 31
-39.5136423301
training end 32
-42.

In [73]:
model(x_test[1])

0.18649344652099104

In [74]:
for h in range(30):
    print(output(x_test[h]))

1
0
1
1
0
1
1
1
0
0
0
1
1
1
0
0
1
0
1
1
0
0
1
1
1
0
1
1
0
0


In [34]:
print(y_test)

[1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 1 1 0 0]


In [52]:
from matplotlib.pyplot import *


-47.260852791858476